### ISSUE TITLE
write block when IOException

### ISSUE THREAD

**Issue by hustchensi** [klauspost/pgzip#11]
we use pgzip for writing to hdfs, write block sometimes.
Using gdb, we found it's blocking at **z.results** channel sending in function **compressCurrent**.
After adding some logs, we found the receiving data goroutine exits because IOException, exactly in the following code:
```
365                 buf := <-r.result
366                 n, err := z.w.Write(buf)
367                 if err != nil {
368                     z.pushError(err)
369                     close(r.notifyWritten)
370                     fmt.Printf("error:%v\n", err)
371                     return
372                 }
```

I think it's needed to implement non-blocking sending **z.results**  in function **compressCurrent**.

**Comment by hustchensi** [comment]
maybe like this:
```
230     for {
231         select {
232         case z.results <- r:
233             break
234         case <-time.After(time.Second * 1):
235             if z.checkError() != nil {
236                 return
237             }
238         }
239     }
```

**Comment by klauspost** [comment]
Thanks for the report. I will investigate, and hopefully have a fix ready soon.
