### ISSUE TITLE
use gzip command or python gzip to uncompress data compressed by pgzip?

### ISSUE THREAD

**Issue by pirDOL** [klauspost/pgzip#18]
backgroud: i have a go service and a python service. In go service, data is compressed by pgzip, but in python service, i tried to use gzip shell command and pytho gzip to uncompress data compressed by pgzip.

error: 
gzip: unexpected end of file
python: IOError: CRC check failed 0xfffafe != 0xb562f324L

question: whether pgzip compressed data is customized, or i need to set some compress config in shell command or python gzip module?

thx

**Comment by klauspost** [comment]
The data is compatible. You are most likely forgetting to close the gzip writer before you close the file.
