### ISSUE TITLE
Compression sizes differ from pigz and gzip...

### ISSUE THREAD

**Issue by sean-** [klauspost/pgzip#19]
Hello.  Thanks for the great library.  I've leveraged this library in a small CLI tool called [`smallz`](https://github.com/sean-/smallz) that basically implements the union of `pigz(1)` and `pv(1)` in the same utility.  It's still early on, but seems to perform competitively with `pigz`.  The UX needs work, and the code looks like it was written over the course of a train and plane ride, but it works.  So thank you.

One of the things that I noticed while testing this is there's a ~2% delta between pigz/gzip and `smallz`.  Is this a known or understood phenomena?  Even when using 1MiB buffer sizes, the quick tests that I ran showed a 200MB vs 205MB delta and I was curious if this was known or needed further investigation.

Thanks in advance!

**Comment by klauspost** [comment]
Yes, compression levels have been re-balanced so the compression options give a more linear response. 

Compression level 1 has been re-written for more speed. This also means that the other levels have been adjusted accordingly and the "default" has been changed to a more appropriate threshold.

See more here: https://blog.klauspost.com/rebalancing-deflate-compression-levels/ (actual numbers are out of date, but the principle still applies)
