### ISSUE TITLE
Missing lines with the uncompression example

### ISSUE THREAD

**Issue by zorino** [klauspost/pgzip#23]
I am trying to uncompress a large file 24GB with the provided example (https://play.golang.org/p/uHv1B5NbDh) and the number of lines computed doesn't match the number expected.

The compressed file has ~94M lines and the output shows ~79M ...

What am I missing here ?

Thanks

**Comment by klauspost** [comment]
That sounds problematic. There shouldn't be any difference whatsoever. I assume `Processed 10013208 entries in 43.484375s, 230271.4 entries/sec.` is from something else.

Obviously transferring 24GB for testing is not really easy. Do you have any information on how the stream was generated?

**Comment by zorino** [comment]
Well I should have said based on the provided example.

Here's a simpler version of the playground example just to count the number of processed entries.

main.go
```
package main

import (
	"bufio"
	"fmt"
	gzip "github.com/klauspost/pgzip"
	//"compress/gzip"
	"os"
	"runtime"
	"strings"
	"time"
)

func main() {
	runtime.GOMAXPROCS(runtime.NumCPU())
	file, err := os.Open("uniprotkb.tsv.gz")
	if err != nil {
		panic(err)
	}
	r, err := gzip.NewReader(file)
	if err != nil {
		panic(err)
	}
	scan := bufio.NewScanner(r)
	t := time.Now()

	n := 0
	for scan.Scan() {
		line := scan.Text()
		strings.Split(line, "\t")
		n++
	}
	d := time.Since(t)
	fmt.Printf("Processed %d entries in %v, %.1f entries/sec.", n, d, float64(n)/(float64(d)/float64(time.Second)))
}

```

The making of the files takes several hours because it downloads from a third party database.

I've put it online temporary so can download it in a reasonable time frame : 

https://bacteriapps.genome.ulaval.ca/share/uniprotkb.tsv.gz

The output for the test
```
$ go run main.go
Processed 79522042 entries in 14m58.97062232s, 88459.0 entries/sec.

$ zcat uniprotkb.tsv.gz | wc -l
94327475
```

Thanks

**Comment by klauspost** [comment]
Thanks! It does seem like it only downloads at about 100KB/s, so I don't have any good way to download it. I should have plenty of bandwidth available, so I don't know if you have any other option for sharing it.

Maybe try if you can send it to me here: https://www.sendthisfile.com/f.jsp?id=Pm0SfqwTVaSfhj9xXrpYeqfs - it should go to me, and I can upload at 150MB/s.

**Comment by zorino** [comment]
I did a test with narrower lines and 100M entries and it processed it all correctly, could it be because some lines in my original gz file are very wide ?

If it's the case how could I process those ?

Unfortunately downloading the file on my computer to upload it back is also really slow, might try this link instead : 

http://perso.genome.ulaval.ca/~deraspem/metaprot/uniprotkb.tsv.gz

**Comment by klauspost** [comment]
Got it - left the computer on while at work and it seems to have downloaded fine. I'll run some tests and get back to you. You can remove the links/files if you want to.

**Comment by klauspost** [comment]
Using both I get `Processed 79522042 entries in 12m59.7100024s, 101989.3 entries/sec.`

So are you sure that pgzip is causing any difference?

**Comment by klauspost** [comment]
I compared the scan results line by line and the pgzip matches the stdlib exactly.

So whatever beef you have, you'll have to take out on the stdlib scanner ;)

**Comment by zorino** [comment]
Indeed the scanner skips tokens that are too long for the buffer...

I've increased the size of the buffer and now all the rows are counted.

Sorry about that, I'm closing the issue and thanks for the support.
