### ISSUE TITLE
pgzip.Writer causes panics in bufio.Write

### ISSUE THREAD

**Issue by ajm188** [klauspost/pgzip#32]
When pgzip's `Writer` is used as a `bufio.Writer`, calls to `Write` can result in panics like:

```
bufio: writer returned negative count from Write
```

which come from [this bit of code in bufio](https://golang.org/src/bufio/bufio.go):

```go
var errNegativeWrite = errors.New("bufio: writer returned negative count from Write")

// writeBuf writes the Reader's buffer to the writer.
func (b *Reader) writeBuf(w io.Writer) (int64, error) {
    n, err := w.Write(b.buf[b.r:b.w])
    if n < 0 {
        panic(errNegativeWrite)
    }
    b.r += n
    return int64(n), err
}
```

This seems to be due to the section of `Write` that actually writes the compressed data to the underlying buffer, definitely _at least_ during the first iteration, and possibly others. The issue is with [this return](https://github.com/klauspost/pgzip/blob/master/gzip.go#L407-L409):

```go
if err := z.checkError(); err != nil {
	return len(p) - len(q) - length, err

}
```

On the first iteration of this loop `q := p`, and length is a positive integer, so this will always return a negative number, causing `bufio` to panic rather than to propagate the error back to the caller.

I think a simple fix here is to return the max of 0 and that value.

**Comment by klauspost** [comment]
Thanks for the detailed analysis.

AFAICT returning `len(p) - len(q)` would also be safe. It doesn't matter much what exactly it is, since it probably hasn't been compressed anyway, but of course it shouldn't be negative.

**Comment by ajm188** [comment]
That sounds good to me as well.
