### ISSUE TITLE
License is not "MIT License" anymore

### ISSUE THREAD

**Issue by cfiderer** [klauspost/pgzip#46]
The change introduced with PR #31 breaks GitHub license detection, the license in this project is not detected as the MIT License anymore.

"Confusing Github" sounds strange, as GitHub properly detects the license in [klauspost/asmfmt](https://github.com/klauspost/asmfmt/blob/master/LICENSE) as the MIT License.

**Comment by klauspost** [comment]
I don't really care. Feel free to send a PR.
