### ISSUE TITLE
OSError: Not a gzipped file (b'i\xdb' or b'\xae\x82') or 'Ran out of input' with decompress

### ISSUE THREAD

**Issue by tle4336** [klauspost/pgzip#55]
@klauspost Dear Mr. Post , I'm currently encountering a very weird issue running on UNIX system in a Docker container using `pgzip`. More specifically, I kept bumping into either the `Ran out of input` or `OSError: Not a gzipped file (b'i\xdb' or b'\xae\x82', etc)` with the following two lines of codes: 
`with open([path to .gz file], "rb", thread=8, blocksize=2*10**8)  as fr:
    pickle.loads(blosc.decompress(fr.read()))`

Could you please help look into this issue? I did not encounter this error on Windows 10, but I would love to use this package on UNIX system.

**Comment by klauspost** [comment]
I think you may be on the wrong repo. This is a Go package.
