### ISSUE TITLE
Is the output gzip file a concatenation of gzip blocks?

### ISSUE THREAD

**Issue by shenwei356** [klauspost/pgzip#57]
Hi Klaus, 

First, I'd like to thank you for this great package, I've used it in several tools of mine.
As the title said, I'm not sure if the output gzip file is a concatenation of gzip blocks. After reading the source code, I think the answer is no. But I'm not sure.

ref: https://github.com/shenwei356/seqkit/issues/443

Best,
Wei

**Comment by klauspost** [comment]
pgzip uses concatenated *deflate* blocks. Blocks back-reference previous blocks, which is why there is no practical compression loss.  Followed up in your issue.
