### ISSUE TITLE
rapidgzip

### ISSUE THREAD

**Issue by karelbilek** [klauspost/pgzip#58]
I am now looking at this code, and it seems they somehow managed to parallelize gzip decompression

https://github.com/mxmlnkn/rapidgzip

https://arxiv.org/abs/2308.08955

I see crazy speedup when I use it. It's in C++ (the python stuff is just sprinkle on top; the actual code is all C++).

Unfortunately, my zero knowledge of decompression algorithms prevents me from porting it to go, and my zero knowledge of the python/cmake stuff prevents me from just "slap it" onto go code with cgo :D

**Comment by klauspost** [comment]
Also, there is  [bgzf](https://pkg.go.dev/github.com/biogo/hts/bgzf) for doing parallel gzip decompression with an index.

**Comment by karelbilek** [comment]
Thanks for a quick reply. Understandable.

**Comment by dolzenko** [comment]
@klauspost out of curiosity, what do you think is the proper use case for gzip then?

**Comment by klauspost** [comment]
@dolzenko Compatibility is the only thing that comes to mind. deflate/gzip can be read/written by pretty much everything.

* zstandard: Beats deflate at pretty much everything. Very high compatibility.
* LZ4/Snappy/S2: Extremely high decompression speed.
* LZMA (7z, xz): Beats most (non-experimental) at compression ratio. Very slow decomp speed. Few implementations.

For development I don't think I would rarely chose deflate over anything, unless compatibility is somehow key.
