### ISSUE TITLE
Make benchmark comparison pgzip vs pigz

### ISSUE THREAD

**Issue by romiras** [klauspost/pgzip#9]
Hi Klaus,
can you make benchmark comparison for such parameters as compression speed, compression level, memory usage between your implementation of **pgzip** and latest **pigz** on various sets of files? For example, on Calgary Corpus.

**Comment by klauspost** [comment]
I have some data here: https://docs.google.com/spreadsheets/d/1nuNE2nPfuINCZJRMt6wFWhKpToF95I47XjSsc-1rbPQ/edit#gid=1577451957

See (medium/rebalanced) for Matt Mahoneys 10GB corpus (Calgary is too small for it to make sense) - there is pigz at the bottom.

**Comment by romiras** [comment]
@klauspost Thank you for comprehensive comparison.
